apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec: 
      containers:
      - name: mongodb
        image: mongo:5.0.5
        env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: myuser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: supersecret
        ports:
          - containerPort: 27017

--- 

apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web2
  template:
    metadata:
      labels:
        app: web2
    spec:
      containers:
      - name: web2
        image: fabiogouw/rotten-potatoes:v1
        ports:
        - containerPort: 5000
        env:
          - name: MONGODB_DB
            value: admin
          - name: MONGODB_HOST
            value: mongodb
          - name: MONGODB_PORT
            value: "27017"
          - name: MONGODB_USERNAME
            value: myuser
          - name: MONGODB_PASSWORD
            value: supersecret

---

apiVersion: v1
kind: Service
metadata:
  name: web2
spec:
  selector:
    app: web2
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000
  type: LoadBalancer
